name: Sync HotelManagement Repository

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "Third Year/3-2/Software Engineering Project/HotelManagement/**"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CSE Repository
        uses: actions/checkout@v4

      - name: Clone HotelManagement Repository
        run: |
          git clone https://x-access-token:${{ secrets.HOTEL_REPO_TOKEN }}@github.com/Marwanthe0/HotelManagement.git hotel

      - name: Copy Project Files
        run: |
          rm -rf hotel/*
          rm -rf hotel/.github

          rsync -a --delete \
          "Third Year/3-2/Software Engineering Project/HotelManagement/" \
          hotel/

      - name: Commit & Push
        working-directory: hotel
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A

          if git diff --cached --quiet; then
            echo "No changes detected."
            exit 0
          fi

          git commit -m "Auto sync from CSE"

          git remote remove origin

          git remote add origin https://x-access-token:${{ secrets.HOTEL_REPO_TOKEN }}@github.com/Marwanthe0/HotelManagement.git

          git push -u origin HEAD:main