name: Sync HotelManagement Repository

on:
  push:
    branches:
      - main
    paths:
      - 'Third Year/3-2/Software Engineering Project/HotelManagement/**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CSE Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push HotelManagement Folder
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: https://x-access-token:${{ secrets.HOTEL_REPO_TOKEN }}@github.com/Marwanthe0/HotelManagement.git

        with:
          subdirectory: "Third Year/3-2/Software Engineering Project/HotelManagement"
          branch: main
          repository: ${{ env.REPO }}